
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.15
    container_name: elasticsearch
    env_file:
      - ../../.env
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - logging


  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.15
    container_name: logstash
    env_file:
      - ../../.env
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    ports:
      - "12201:12201/udp"
    depends_on:
      - elasticsearch
    networks:
      - logging
      - app-network


  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.15
    container_name: kibana
    env_file:
      - ../../.env
    ports:
      - "5601:5601"
    volumes:
      - kibana-data:/usr/share/kibana/data
    depends_on:
      - elasticsearch
    networks:
      - logging


  setup:
    image: curlimages/curl:latest
    container_name: elk-setup
    env_file:
      - ../../.env
    volumes:
      - ./elasticsearch/ilm-policy.json:/ilm-policy.json:ro
      - ./elasticsearch/setup-ilm.sh:/setup-ilm.sh:ro
    command: sh /setup-ilm.sh
    depends_on:
      - elasticsearch
    networks:
      - logging
    restart: "no"

volumes:
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local

networks:
  logging:
    external: true
    name: logging
  app-network:
    external: true
    name: network
