name: user_service_ci

on:
    push:
        branches: [ "main_ums", "main", "ums_ci" ]
        # Triggers only if files in this directory change
        paths:
            - 'src/backend/user-service/**'
    pull_request:
        branches: [ "main" ]
        paths:
            - 'src/backend/user-service/**'

jobs:
    test_user_service:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: src/backend/user-service
        steps:
            - uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20'
            - run: npm install
            - run: cp .example.env .env
            - run: npx prisma generate && DATABASE_URL="file:./test.db" npx prisma migrate dev
            - run: npm run type-check 
            - run: npm test
    